GET https://jsonplaceholder.typicode.com/posts/


###

POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
  "title": "Hello",
  "body": "Testing REST client",
  "userId": 1
}
